![](https://cdn.discordapp.com/attachments/670023265455964198/1104171789069860864/BeautifulLogo.png)

![Documentation](https://prooheckcp.github.io//RobloxStateMachines) | ![Source](https://github.com/prooheckcp/RobloxStateMachines)