name: Wally

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, development, Settingup-workflow]

jobs:

  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python my_script.py

    - name: Publish
      run: |
        python print("Hello World")

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0

